apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
data:
  blue-green.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export let options = {
      vus: 20,
      duration: '20s',
    };

    export default function () {
      const res = http.get('http://content-service.default.svc.cluster.local/');
      check(res, { 'status 200': (r) => r.status === 200 });
      sleep(1);
    }

  canary.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export let options = {
      vus: 10,
      duration: '15s',
    };

    export default function () {
      const res = http.get('http://content-service-canary.default.svc.cluster.local/');
      check(res, { 'status 200': (r) => r.status === 200 });
      sleep(1);
    }
