apiVersion: batch/v1
kind: Job
metadata:
  name: k6-canary
spec:
  template:
    metadata:
      labels:
        job: k6-canary
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: local/k6:arm64
          command: ["k6", "run", "/scripts/canary.js"]
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts
  backoffLimit: 1
