apiVersion: v1
kind: Service
metadata:
  name: content-service
  labels:
    app: content
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: content
    version: blue
  type: ClusterIP
